version: '2'
services:
  gocdio-server:
    labels:
      gocd.role: server
    tty: true
    image: gocd/gocd-server:v17.3.0
    volumes:
    - godata:/godata
    volume_driver: ${VOLUME_DRIVER}
    tty: true
    ports:
    - 8153:8153
    - 8154:8154
    labels:
      io.rancher.container.hostname_override: container_name
